# Use postgres/example user/password credentials
version: '3.8'

services:
  db:
    image: postgres:15.2-bullseye
    restart: always
    environment:
      POSTGRES_USER: postgres_dev_user
      POSTGRES_PASSWORD: postgres_dev_passwd
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "54327:5432"

volumes:
  pgdata:
